version: "3.9"

services:
  mojo-backend-engine:
    build:
      context: .
      # Correct path to the backend Dockerfile
      dockerfile: mojobackend.dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/status || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - mojo-backend-dbstore:/home/nonroot/mojobuilder/db
    networks:
      - mojo-subnetwork

  mojo-frontend-app:
    build:
      context: .
      # Correct path to the frontend Dockerfile
      dockerfile: mojobuilder.dockerfile
      args:
        - VITE_API_BASE_URL=http://mojo-backend-engine:3000  # INTERNAL Docker network URL
    environment:
      - VITE_API_BASE_URL=http://0.0.0.0:1337  # External access when running locally
    depends_on:
      - mojo-backend-engine
    expose:
      - "1337"
    ports:
      - "1337:1337"
    networks:
      - mojo-subnetwork

networks:
  mojo-subnetwork:

volumes:
  mojo-backend-dbstore: